title: "Business Central Dokumentacija"
description: "Detaljno uputstvo za integraciju sa brzom poštom"
theme: "just-the-docs"

# Omogući sidebar
just_the_docs:
  search_enabled: true
  navigation:
    - title: "Početna"
      url: /
    - title: "Instalacija"
      url: /instalacija
    - title: "Podešavanje"
      url: /podesavanje
    - title: "Testiranje"
      url: /testiranje
