title: "Business Central Dokumentacija"
description: "Detaljno uputstvo za integraciju sa brzom poštom"
theme: "just-the-docs"

# Omogućavanje pretrage
search_enabled: true

# Navigacija
nav_order: 1
aux_links:
  "GitHub Repo": "https://github.com/tvoj-repo"

# Omogućavanje tamne teme
color_scheme: dark

# Definisanje navigacije
just_the_docs:
  collections:
    docs:
      name: "Dokumentacija"
      nav_order: 1
